import './globals.css';
import type { Metadata } from 'next';
import { currentLocale } from 'next-i18n-router';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang={currentLocale()}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
