import './globals.css';
import type { Metadata } from 'next';
import { currentLocale } from 'next-i18n-router';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

// If using next-i18n-router config option `routingStrategy: dynamicSegment`,
// you can generate pages at build time for all locales.

// export function generateStaticParams() {
//   return i18nConfig.locales.map(locale => { locale });
// }

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang={currentLocale()}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
